'''
// bad for 7.3
[Operation]GolanHeights
[Operation]Kamchatka
[Operation]Pyrenees
[Operation]City
[Operation]RockyPillars
[Operation]BattleForVietnam
[Operation]Sinai
[Operation]Moscow
[AlternateHistory]Spain
'''
whitelistedmap = [
    r"airshadowed\[AirBattle]France1944",
    r"airshadowed\[AirBattle]HurtgenSecondBattle",
    r"airshadowed\[AirBattle]Moscow1941",
    r"airshadowed\[AirBattle]OperationIskra",
    r"airshadowed\[AlternateHistory]BerlinSummer1945",
    r"airshadowed\[AlternateHistory]KrymskSummer1945",
    r"airshadowed\[Event]OperationUranus",
    r"airshadowed\[FrontLine]Korsun",
    r"airshadowed\[FrontLine]Ladoga",
    r"airshadowed\[MilitaryExercise]PreparationForLandingOnHokkaido",
    r"airshadowed\[Operation]BattleAtMalta",
    r"airshadowed\[Operation]BattleForBastogne",
    r"airshadowed\[Operation]BattleForTheRhine",
    r"airshadowed\[Operation]BattleOfTunisia",
    r"airshadowed\[Operation]Berlin",
    r"airshadowed\[Operation]BourbonIsland",
    r"airshadowed\[Operation]Britain",
    r"airshadowed\[Operation]Bulge",
    r"airshadowed\[Operation]ChinaCivilWar1946",
    r"airshadowed\[Operation]DefendingStalingrad",
    r"airshadowed\[Operation]ElAlamein",
    r"airshadowed\[Operation]Hurtgen",
    r"airshadowed\[Operation]KamchatkaEast",
    r"airshadowed\[Operation]KhalkhinGol",
    r"airshadowed\[Operation]Korea",
    r"airshadowed\[Operation]Korsun",
    r"airshadowed\[Operation]Kuban",
    r"airshadowed\[Operation]Kursk",
    r"airshadowed\[Operation]LadogaWinter1941",
    r"airshadowed\[Operation]LakeLadoga",
    r"airshadowed\[Operation]Malta",
    r"airshadowed\[Operation]Moscow42ndKilometer",
    r"airshadowed\[Operation]MoscowNaro-Fominsk",
    r"airshadowed\[Operation]MoscowSerpukhov",
    r"airshadowed\[Operation]MozdokWinter1943",
    r"airshadowed\[Operation]Norway",
    r"airshadowed\[Operation]Poland",
    r"airshadowed\[Operation]RoadToGrozny",
    r"airshadowed\[Operation]Ruhr",
    r"airshadowed\[Operation]Sicily",
    r"airshadowed\[Operation]Smolensk1941",
    r"airshadowed\[Operation]Smolensk1943",
    r"airshadowed\[Operation]Zhengzhou",
]
specialmapdetectors = {}
