from .autofreshmap_configmap_importref import *

whitelistedmap = [
    "AshRiver",
    "BattleOfHurtgenForestConquest#1",
    "BattleOfHurtgenForestDomination#1",
    "Berlin",
    "Carpathians",
    "EasternEurope",
    "EuropeanProvince",
    "FieldsOfNormandy",
    "FieldsOfPoland(winter)",
    "FieldsOfPoland",
    "Finland",
    "FireArc",
    "FrozenPass",
    "FuldaDomination#1",
    "FuldaDomination#2",
    "Japan",
    "Jungle",
    "Karelia",
    "Kurban",
    "MaginotLineDomination#1",
    "MaginotLineDomination#1Winter",
    "MaginotLineDomination#2",
    "MaginotLineDomination#2Winter",
    "MiddleEast",
    "Mozdok#1",
    "Mozdok#2",
    "Normandy",
    "Poland(winter)",
    "Poland",
    "SandsOfSinai",
    "SandsOfTunisia",
    "SecondBattleOfElAlameinConquest#1",
    "Sinai",
    "SurroundingsOfVolokolamsk",
    "TestSite-2271",
    "Tunisia",
    "Volokolamsk",
]

specialmapdetectors = {
}
