from .autofreshmap_configmap_importref import *

smalls = [
    r"air\[AirBattle]France1944",
    # r"air\[AirBattle]HurtgenSecondBattle",
    r"air\[AirBattle]Moscow1941",
    r"air\[AirBattle]OperationIskra",
    r"air\[AlternateHistory]Afghanistan",
    r"air\[AlternateHistory]BerlinSummer1945",
    r"air\[AlternateHistory]KrymskSummer1945",
    r"air\[AlternateHistory]Spain",
    r"air\[Event]OperationUranus",
    r"air\[FrontLine]Korsun",
    r"air\[FrontLine]Kuban",
    r"air\[FrontLine]Kursk",
    r"air\[FrontLine]Ladoga",
    r"air\[FrontLine]Mozdok",
    r"air\[MilitaryExercise]PreparationForLandingOnHokkaido",
    r"air\[Operation]Afghanistan",
    r"air\[Operation]Bastogne(LightVehicles)",
    r"air\[Operation]BattleAtMalta",
    r"air\[Operation]BattleForBastogne",
    r"air\[Operation]BattleForSpain",
    r"air\[Operation]BattleForTheRhine",
    r"air\[Operation]BattleForVietnam",
    r"air\[Operation]BattleOfTunisia",
    # r"air\[Operation]Berlin",
    r"air\[Operation]BourbonIsland",
    r"air\[Operation]Britain",
    #r"air\[Operation]Bulge",
    r"air\[Operation]CentralTunisia(LightVehicles)",
    r"air\[Operation]ChinaCivilWar1946",
    r"air\[Operation]City",
    r"air\[Operation]Cochinchina(LightVehicles)",
    r"air\[Operation]ConsolidationOfPositionsOnSicily(LightVehicles)",
    r"air\[Operation]Counteroffensive(LightVehicles)",
    r"air\[Operation]CounterstrikeUnderSmolensk(LightVehicles)",
    r"air\[Operation]DefendingStalingrad",
    r"air\[Operation]ElAlamein",
    r"air\[Operation]Essen(LightVehicles)",
    r"air\[Operation]GolanHeights(AirSpawns)",
    r"air\[Operation]GolanHeights",
    r"air\[Operation]Guadalcanal",
    r"air\[Operation]HenanProvince(LightVehicles)",
    r"air\[Operation]Honolulu(LightVehicles)",
    #r"air\[Operation]Hurtgen",
    r"air\[Operation]IwoJima",
    r"air\[Operation]Kamchatka",
    r"air\[Operation]KamchatkaEast",
    r"air\[Operation]KhalkhinGol",
    r"air\[Operation]Korea",
    #r"air\[Operation]Korsun",
    r"air\[Operation]Kuban",
    r"air\[Operation]Kursk",
    # r"air\[Operation]LadogaWinter1941",
    # r"air\[Operation]LaizhouBay",
    r"air\[Operation]LakeLadoga(LightVehicles)",
    r"air\[Operation]LakeLadoga",
    r"air\[Operation]Malta",
    r"air\[Operation]Midway",
    r"air\[Operation]Moscow",
    r"air\[Operation]Moscow42ndKilometer",
    r"air\[Operation]MoscowNaro-Fominsk",
    r"air\[Operation]MoscowSerpukhov",
    r"air\[Operation]Mozdok(LightVehicles)",
    r"air\[Operation]MozdokWinter1943",
    r"air\[Operation]MysteriousValley(AirSpawns)",
    r"air\[Operation]MysteriousValley.Spaceport",
    r"air\[Operation]NearEast(LightVehicles)",
    r"air\[Operation]NewGuinea",
    r"air\[Operation]Norway",
    r"air\[Operation]Peleliu",
    r"air\[Operation]Poland",
    r"air\[Operation]PortMoresby(LightVehicles)",
    r"air\[Operation]Pyrenees",
    r"air\[Operation]RoadToGrozny",
    r"air\[Operation]RockyCanyon",
    r"air\[Operation]RockyPillars",
    #r"air\[Operation]Ruhr",
    r"air\[Operation]Saipan",
    r"air\[Operation]Sicily",
    r"air\[Operation]Sinai",
    r"air\[Operation]Smolensk1941",
    r"air\[Operation]Smolensk1943", #G
    r"air\[Operation]SoutheasternCity",
    r"air\[Operation]Spain",
    r"air\[Operation]TheLastBattleOfKhalkhynGol(LightVehicles)",
    r"air\[Operation]Vietnam",
    r"air\[Operation]WakeIsland(LightVehicles)",
    r"air\[Operation]YooPassage(LightVehicles)",
    r"air\[Operation]Zhengzhou",
]

mapAcceptorParam = MapAcceptorParam(
    whitelistedmap=smalls
)